<script setup lang="ts">
import { ref } from 'vue'
import { Message } from '@arco-design/web-vue'
import { bookApi, familyApi, personApi } from '../api'
import type { Book, FamilyMember, GraphData, Person } from '../types'
const props = defineProps<{ books: Book[]; members: FamilyMember[]; persons: Person[]; familyId?: string; personName: (id: string) => string; formatTime: (value: string) => string }>()
const emit = defineEmits<{ create: []; open: [book: Book]; refresh: [] }>()
const selected = ref<Book | null>(null); const collaborators = ref<FamilyMember[]>([]); const collaboratorID = ref(''); const busy = ref(false)
const relationBook = ref<Book | null>(null); const relationVisible = ref(false); const graph = ref<GraphData | null>(null)
const relationForm = ref({ fromPersonID: '', toPersonID: '', relationType: 'FATHER', customName: '', note: '' })
const relationNames: Record<string, string> = { FATHER: '父亲', MOTHER: '母亲', SON: '儿子', DAUGHTER: '女儿', HUSBAND: '丈夫', WIFE: '妻子', BROTHER: '兄弟', SISTER: '姐妹', GRANDFATHER: '祖父', GRANDMOTHER: '祖母', GRANDCHILD: '孙辈', UNCLE: '叔伯', AUNT: '姑姨', NEPHEW_NIECE: '侄辈', CUSTOM: '自定义' }
const relationText = (edge: any) => edge.custom_name || relationNames[edge.relation_type] || edge.relation_type
async function manage(book: Book) { try { selected.value = await bookApi.get(book.id); collaborators.value = (await bookApi.collaborators(book.id)).map((u) => props.members.find((m) => m.user_id === u.id) || ({ ...u, id: u.id, user_id: u.id, role: 'viewer', status: 'active', joined_at: '' } as FamilyMember)); collaboratorID.value = '' } catch (e: any) { Message.error(e.message) } }
async function remove(book: Book) { try { await bookApi.remove(book.id); emit('refresh'); Message.success('家谱已删除') } catch (e: any) { Message.error(e.message) } }
async function addCollaborator() { if (!selected.value || !collaboratorID.value || busy.value) return; busy.value = true; try { await bookApi.addCollaborator(selected.value.id, collaboratorID.value); await manage(selected.value) } catch (e: any) { Message.error(e.message) } finally { busy.value = false } }
async function removeCollaborator(id: string) { if (!selected.value) return; try { await bookApi.removeCollaborator(selected.value.id, id); await manage(selected.value) } catch (e: any) { Message.error(e.message) } }
async function manageRelations(book: Book) {
  relationBook.value = book; relationForm.value = { fromPersonID: book.root_person_id || props.persons[0]?.id || '', toPersonID: '', relationType: 'FATHER', customName: '', note: '' }; relationVisible.value = true
  if (props.familyId) { try { graph.value = await familyApi.graph(props.familyId, relationForm.value.fromPersonID) } catch (e: any) { Message.error(e.message) } }
}
async function saveRelation() {
  if (!relationForm.value.fromPersonID || !relationForm.value.toPersonID || relationForm.value.fromPersonID === relationForm.value.toPersonID) return
  try { await personApi.relation(relationForm.value.fromPersonID, { toPersonID: relationForm.value.toPersonID, relationType: relationForm.value.relationType, customName: relationForm.value.customName, note: relationForm.value.note, familyId: props.familyId }); if (props.familyId) graph.value = await familyApi.graph(props.familyId, relationForm.value.fromPersonID); emit('refresh'); Message.success('家族关系已建立') } catch (e: any) { Message.error(e.message) }
}
async function removeRelation(id: string) { try { await personApi.removeRelation(id); if (props.familyId) graph.value = await familyApi.graph(props.familyId, relationForm.value.fromPersonID); emit('refresh'); Message.success('关系已删除') } catch (e: any) { Message.error(e.message) } }
</script>
<template>
  <div class="section-head"><h2>家谱文库</h2><a-button type="primary" @click="emit('create')">新建家谱</a-button></div><div v-if="props.books.length" class="book-grid"><div v-for="book in props.books" :key="book.id" class="book-card"><div class="book-cover">{{ book.title }}</div><p>关联人物：{{ book.root_person_id ? personName(book.root_person_id) : '未关联' }} · {{ formatTime(book.updated_at) }}</p><div class="action-row"><a-button type="text" @click="emit('open', book)">打开编辑</a-button><a-button @click="manageRelations(book)">维护关系</a-button><a-button @click="manage(book)">协作者</a-button><a-popconfirm content="确定删除家谱？" @ok="remove(book)"><a-button status="danger">删除</a-button></a-popconfirm></div></div></div><a-empty v-else />
  <a-modal :visible="!!selected" title="家谱协作者" :footer="false" @cancel="selected = null"><div v-if="props.members.filter((m) => !collaborators.some((c) => c.user_id === m.user_id)).length" class="action-row"><a-select v-model="collaboratorID" placeholder="选择家族成员" style="flex:1"><a-option v-for="m in props.members.filter((m) => !collaborators.some((c) => c.user_id === m.user_id))" :key="m.user_id" :value="m.user_id">{{ m.display_name }}（{{ m.role }}）</a-option></a-select><a-button :disabled="!collaboratorID" :loading="busy" @click="addCollaborator">添加</a-button></div><p v-else class="edit-hint" style="margin:6px 0 14px">暂无可添加的家族成员——家谱协作者必须是该家族的成员。请先到「家族成员」页邀请家人加入，加入后即可在此添加为协作者。</p><div v-for="m in collaborators" :key="m.user_id" class="member"><span>{{ m.display_name || m.email }}</span><a-button type="text" status="danger" @click="removeCollaborator(m.user_id)">移除</a-button></div></a-modal>
  <a-modal v-model:visible="relationVisible" :title="`维护关系${relationBook ? ` · ${relationBook.title}` : ''}`" :width="760" :footer="false"><div class="relation-form-grid"><a-select v-model="relationForm.fromPersonID" allow-search placeholder="输入姓名搜索人物 A" @change="props.familyId && familyApi.graph(props.familyId, String(relationForm.fromPersonID)).then((value) => graph = value)"><a-option v-for="p in props.persons" :key="p.id" :value="p.id">{{ p.name }}</a-option></a-select><a-select v-model="relationForm.relationType" allow-search placeholder="搜索关系类型"><a-option v-for="(label, value) in relationNames" :key="value" :value="value">{{ label }}</a-option></a-select><a-select v-model="relationForm.toPersonID" allow-search placeholder="输入姓名搜索人物 B"><a-option v-for="p in props.persons.filter(item => item.id !== relationForm.fromPersonID)" :key="p.id" :value="p.id">{{ p.name }}</a-option></a-select><a-input v-if="relationForm.relationType === 'CUSTOM'" v-model="relationForm.customName" placeholder="自定义关系名称" /><a-input v-model="relationForm.note" placeholder="备注（可选）" /><a-button type="primary" @click="saveRelation">建立关系</a-button></div><div v-if="graph" class="relation-list"><div v-for="edge in graph.edges.filter((item, index, all) => all.findIndex(other => [other.from_person_id, other.to_person_id].sort().join(':') === [item.from_person_id, item.to_person_id].sort().join(':')) === index)" :key="edge.id" class="member"><span>{{ props.personName(edge.from_person_id) }} · {{ relationText(edge) }} · {{ props.personName(edge.to_person_id) }}</span><a-popconfirm content="确定删除该关系及其反向关系？" @ok="removeRelation(edge.id)"><a-button status="danger">删除</a-button></a-popconfirm></div><a-empty v-if="!graph.edges.length" description="暂无关系" /></div></a-modal>
</template>
