<script setup lang="ts">
import { ref } from 'vue'
import { Message } from '@arco-design/web-vue'
import { apiOrigin } from '../api/client'; import { personApi, photoApi } from '../api'
import type { Person, Photo } from '../types'
const props = defineProps<{ photos: Photo[]; persons: Person[]; personName: (id: string) => string; formatTime: (value: string) => string }>(); const emit = defineEmits<{ upload: []; refresh: [] }>()
const selected = ref<Photo | null>(null); const linked = ref<Person[]>([]); const personID = ref(''); const photoUrl = (path: string) => new URL(path, `${apiOrigin}/`).toString()
async function open(p: Photo) { try { selected.value = await photoApi.get(p.id); linked.value = await photoApi.persons(p.id); personID.value = '' } catch (e: any) { Message.error(e.message) } }
async function save() { if (!selected.value) return; try { await photoApi.update(selected.value.id, selected.value); selected.value = null; emit('refresh'); Message.success('照片资料已保存') } catch (e: any) { Message.error(e.message) } }
async function remove(p: Photo) { try { await photoApi.remove(p.id); selected.value = null; emit('refresh'); Message.success('照片已删除') } catch (e: any) { Message.error(e.message) } }
async function associate(remove = false, id = personID.value) { if (!selected.value || !id) return; try { if (remove) await photoApi.removePerson(selected.value.id, id); else await photoApi.addPerson(selected.value.id, id); linked.value = await photoApi.persons(selected.value.id); personID.value = ''; emit('refresh') } catch (e: any) { Message.error(e.message) } }
</script>
<template><div class="section-head"><h2>家族照片</h2><a-button type="primary" @click="emit('upload')">上传照片</a-button></div><div v-if="props.photos.length" class="book-grid"><div v-for="p in props.photos" :key="p.id" class="book-card"><img :src="photoUrl(p.path)" :alt="p.caption || p.original_name" style="width:100%;height:118px;object-fit:cover"><strong>{{ p.caption || p.original_name }}</strong><p>{{ personName(p.person_id) }} · {{ formatTime(p.created_at) }}</p><div class="action-row"><a-button @click="open(p)">详情编辑</a-button><a-popconfirm content="确定删除照片？" @ok="remove(p)"><a-button status="danger">删除</a-button></a-popconfirm></div></div></div><a-empty v-else /><a-modal :visible="!!selected" title="照片资料与人物" :footer="false" @cancel="selected = null"><img v-if="selected" :src="photoUrl(selected.path)" style="width:100%;max-height:240px;object-fit:contain"><a-form v-if="selected" :model="selected" layout="vertical"><a-form-item label="说明"><a-input v-model="selected.caption" /></a-form-item><a-form-item label="分类"><a-input v-model="selected.category" /></a-form-item><a-form-item label="拍摄时间"><a-input v-model="selected.taken_at" /></a-form-item><a-form-item label="地点"><a-input v-model="selected.location" /></a-form-item><a-button type="primary" @click="save">保存</a-button></a-form><h3>关联人物</h3><div class="action-row"><a-select v-model="personID" placeholder="选择人物" style="flex:1"><a-option v-for="p in props.persons.filter(p => !linked.some(l => l.id === p.id))" :key="p.id" :value="p.id">{{ p.name }}</a-option></a-select><a-button :disabled="!personID" @click="associate()">添加</a-button></div><div v-for="p in linked" :key="p.id" class="member"><span>{{ p.name }}</span><a-button type="text" status="danger" @click="associate(true, p.id)">移除</a-button></div></a-modal></template>
